- name: add Docker repo
  yum_repository:
    name: docker_stable
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg
  become: yes
  become_user: root
- name: install Docker and dependencies
  yum:
    name: ["docker-ce", "docker-ce-cli", "containerd.io", "python3-pip"] 
    state: latest
  become: yes
  become_user: root
- name: install Docker SDK
  command: pip3 install docker
  become: yes
  become_user: root
- name: enable and start Docker systemd service
  systemd:
    name: docker 
    state: started
    enabled: yes
  become: yes
  become_user: root