global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "elrond-node-metrics"
    static_configs:
      - targets: ["10.44.2.2:8090"]
    metrics_path: "/node/metrics"
  - job_name: "elrond-machine-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["10.44.2.3:9100"]