---
name: bitcoin
state: present
topology: p2m
connections:
  monitoring_node:
    connect_to:
      bitcoin_node:
        type: tag
        services:
          - node
          - exporter
    state: present
    type: endpoint 
    services:
      - prometheus
      - grafana
  localhost:
    connect_to:
      bitcoin_node:
        type: tag
        services:
          - node
          - exporter
      monitoring_node:
        type: endpoint
        services:
          - prometheus
          - grafana
    state: present
    type: endpoint