- name: bootstrap nodes
  hosts: common
  roles:
    - common_setup
    - docker
- name: add user to Docker group
  hosts: monitoring
  tasks:
  - name: add monitoring user to Docker group
    user:
      name: ethereum
      groups: docker
      append: true
    become: yes
    become_user: root
  - name: reset ssh connection
    meta: reset_connection
- name: configure Node firewall
  hosts: node
  tasks:
  - name: add UDP ports
    command: firewall-cmd --add-port=0-65535/udp --permanent --zone=public
  # - name: add P2P port
  #   command: firewall-cmd --add-port=38383/tcp --permanent --zone=public
  - name: reload Firewall
    command: firewall-cmd --reload
- name: create Docker networks
  hosts: common
  roles:
    - create_docker_network
  vars:
    subnet: "10.44.{{ play_hosts.index(inventory_hostname) | int + 1 }}.0/24"
- name: launch Syntropy Agent on localhost
  hosts: localhost
  roles:
    - deploy_agent
  vars:
    SYNTROPY_API_KEY: "{{ SYNTROPY_AGENT_API_KEY }}"
    SYNTROPY_TAGS: "bastion"
    SYNTROPY_AGENT_NAME: "bastion"
    SYNTROPY_PROVIDER: ""
  vars_files:
    - vars/main.yml
- name: launch Syntropy Agent on Ethereum node
  hosts: node
  roles:
    - deploy_agent
  vars:
    SYNTROPY_API_KEY: "{{ SYNTROPY_AGENT_API_KEY }}"
    SYNTROPY_TAGS: "ethereum_nodes"
    SYNTROPY_AGENT_NAME: "ethereum_node_{{ groups['node'].index(inventory_hostname) }}"
    SYNTROPY_PROVIDER: "16"
  vars_files:
    - vars/main.yml
- name: launch Syntropy Agent on Monitoring node
  hosts: monitoring
  roles:
    - deploy_agent
  vars:
    SYNTROPY_API_KEY: "{{ SYNTROPY_AGENT_API_KEY }}"
    SYNTROPY_TAGS: "monitoring"
    SYNTROPY_AGENT_NAME: "monitoring_node"
    SYNTROPY_PROVIDER: "3"
  vars_files:
    - vars/main.yml
- name: Create Ethereum account on Ethereum node
  hosts: node
  tasks:
    - name: create Ethereum user
      user:
        name: ethereum
        shell: /bin/bash
        groups:
          - docker
- name: deploy Ethereum 
  hosts: node 
  roles:
    - deploy_ethereum
  vars_files:
    - vars/main.yml
- name: deploy monitoring
  hosts: monitoring
  roles:
    - deploy_prometheus
    - deploy_grafana
    - deploy_ethnetintel
  vars_files:
    - vars/main.yml
- name: deploy Node exporter
  hosts: node
  roles:
    - deploy_node_exporter
  vars_files:
    - vars/main.yml
- name: create Syntropy Ethereum network
  hosts: localhost
  roles:
    - syntropy_ethereum_network
  vars:
    SYNTROPY_CONTROLLER_URL: "{{ SYNTROPY_CONTROLLER_URL }}"
    SYNTROPY_USERNAME: "{{ SYNTROPY_USERNAME }}"
    SYNTROPY_PASSWORD: "{{ SYNTROPY_PASSWORD }}"
  vars_files:
    - vars/main.yml
