global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets: ["172.20.0.2:9100"]
  - job_name: "validator-metrics-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["172.20.0.3:9615"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["172.21.0.4:9090"]
