---
# install docker

# Create docker group
- name: create docker group
  become: true
  become_user: root
  group:
    name: docker
    state: present

- debug:
    msg: "ansible user_id: {{ansible_user_id}}"

- name: add user to group
  become: true
  become_user: root
  user:
    name: "{{ansible_user_id}}"
    groups: docker
    append: true

##### setup docker

- name: install packages required by docker
  become: true
  apt:
    update_cache: yes
    state: latest
    name:
      - python3-pip
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg-agent
      - software-properties-common
      - python3-setuptools

- name: add docker GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker apt repo
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: install docker
  become: true
  apt:
    update_cache: yes
    state: latest
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: install 'Docker SDK for Python'
  pip:
    name:
      - docker
      - docker-compose
